### ISSUE TITLE
Add Common-Issues search.

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/guide#3]
I'll be adding this bit by bit over the next little while (depending on how much time I have).

**TODO**

- [ ] Implement The [Nuget Package](https://www.nuget.org/packages/CommonIssues.JsonParser/)
- [ ] Add Searching for issue.
- [ ] Add List all issues.
- [ ] Implement Further Resources such as those from MSDN

**Comment by svr333** [comment]
Is this still an issue that awaits to be worked on?

**Comment by DraxCodes** [comment]
It wasn't tbh as I put a hold on it while I judged whether or not it would be needed. 

That being said, I feel after Peter's refactor of the bot architecture, we would need to refactor the service for this anyway. So, while we're at it, may as-well add a direct link to common issues (instead of listing em as it would be rather spammy), we could also implement the MSDN search too as it's a very simple public facing API we can use.

**Comment by svr333** [comment]
I feel like this would be perfect for a LiveShare session :)
